src/Entity/Commune.php
<?php

namespace App\Entity;

use App\Repository\CommuneRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommuneRepository::class)]
class Commune
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 10)]
    private ?string $code = null;

    #[ORM\ManyToOne(inversedBy: 'communes')]
    private ?District $district = null;

    #[ORM\OneToMany(targetEntity: Fokotany::class, mappedBy: 'commune')]
    private Collection $fokotanies;

    #[ORM\OneToMany(targetEntity: Elections::class, mappedBy: 'Commune')]
    private Collection $elections;

    public function __construct()
    {
        $this->fokotanies = new ArrayCollection();
        $this->elections = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): static
    {
        $this->code = $code;

        return $this;
    }

    public function getDistrict(): ?District
    {
        return $this->district;
    }

    public function setDistrict(?District $district): static
    {
        $this->district = $district;

        return $this;
    }

    /**
     * @return Collection<int, Fokotany>
     */
    public function getFokotanies(): Collection
    {
        return $this->fokotanies;
    }

    public function addFokotany(Fokotany $fokotany): static
    {
        if (!$this->fokotanies->contains($fokotany)) {
            $this->fokotanies->add($fokotany);
            $fokotany->setCommune($this);
        }

        return $this;
    }

    public function removeFokotany(Fokotany $fokotany): static
    {
        if ($this->fokotanies->removeElement($fokotany)) {
            // set the owning side to null (unless already changed)
            if ($fokotany->getCommune() === $this) {
                $fokotany->setCommune(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->nom;
    }

    /**
     * @return Collection<int, Elections>
     */
    public function getElections(): Collection
    {
        return $this->elections;
    }

    public function addElection(Elections $election): static
    {
        if (!$this->elections->contains($election)) {
            $this->elections->add($election);
            $election->setCommune($this);
        }

        return $this;
    }

    public function removeElection(Elections $election): static
    {
        if ($this->elections->removeElement($election)) {
            // set the owning side to null (unless already changed)
            if ($election->getCommune() === $this) {
                $election->setCommune(null);
            }
        }

        return $this;
    }

}

src/Entity/District.php
<?php

namespace App\Entity;

use App\Repository\DistrictRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DistrictRepository::class)]
class District
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 10)]
    private ?string $code = null;

    #[ORM\ManyToOne(inversedBy: 'districts')]
    private ?Region $Region = null;

    #[ORM\OneToMany(targetEntity: Commune::class, mappedBy: 'district')]
    private Collection $communes;

    #[ORM\OneToMany(targetEntity: Elections::class, mappedBy: 'District')]
    private Collection $elections;

    public function __construct()
    {
        $this->communes = new ArrayCollection();
        $this->elections = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): static
    {
        $this->code = $code;

        return $this;
    }

    public function getRegion(): ?Region
    {
        return $this->Region;
    }

    public function setRegion(?Region $Region): static
    {
        $this->Region = $Region;

        return $this;
    }

    /**
     * @return Collection<int, Commune>
     */
    public function getCommunes(): Collection
    {
        return $this->communes;
    }

    public function addCommune(Commune $commune): static
    {
        if (!$this->communes->contains($commune)) {
            $this->communes->add($commune);
            $commune->setDistrict($this);
        }

        return $this;
    }

    public function removeCommune(Commune $commune): static
    {
        if ($this->communes->removeElement($commune)) {
            // set the owning side to null (unless already changed)
            if ($commune->getDistrict() === $this) {
                $commune->setDistrict(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->nom;
    }

    /**
     * @return Collection<int, Elections>
     */
    public function getElections(): Collection
    {
        return $this->elections;
    }

    public function addElection(Elections $election): static
    {
        if (!$this->elections->contains($election)) {
            $this->elections->add($election);
            $election->setDistrict($this);
        }

        return $this;
    }

    public function removeElection(Elections $election): static
    {
        if ($this->elections->removeElement($election)) {
            // set the owning side to null (unless already changed)
            if ($election->getDistrict() === $this) {
                $election->setDistrict(null);
            }
        }

        return $this;
    }
}

src/Form/CommuneType.php
<?php

namespace App\Form;

use App\Entity\Commune;
use App\Entity\District;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommuneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('code')
            ->add('district', EntityType::class, [
                'class' => District::class,
                'choice_label' => 'nom',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commune::class,
        ]);
    }
    
}

src/Controller/CommuneController.php
<?php

namespace App\Controller;

use App\Entity\Commune;
use App\Form\CommuneType;
use App\Repository\CommuneRepository;
use App\Repository\DistrictRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/commune')]
class CommuneController extends AbstractController
{
    #[Route('/', name: 'app_commune_index', methods: ['GET'])]
    public function index(CommuneRepository $communeRepository): Response
    {
        return $this->render('commune/index.html.twig', [
            'communes' => $communeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_commune_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $commune = new Commune();
        $form = $this->createForm(CommuneType::class, $commune);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($commune);
            $entityManager->flush();

            return $this->redirectToRoute('app_commune_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('commune/new.html.twig', [
            'commune' => $commune,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commune_show', methods: ['GET'])]
    public function show(Commune $commune, DistrictRepository $districtRepository): Response
    {
        return $this->render('commune/show.html.twig', [
            'commune' => $commune,
            'district'=> $districtRepository->findAll()
        ]);
    }

    #[Route('/{id}/edit', name: 'app_commune_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Commune $commune, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CommuneType::class, $commune);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_commune_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('commune/edit.html.twig', [
            'commune' => $commune,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commune_delete', methods: ['POST'])]
    public function delete(Request $request, Commune $commune, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commune->getId(), $request->request->get('_token'))) {
            $entityManager->remove($commune);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_commune_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/commune/_delete_form.html.twig
<form method="post" action="{{ path('app_commune_delete', {'id': commune.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commune.id) }}">
    <button class="btn btn-outline-danger"
    style="position:absolute;
    right:20px">Delete</button>
</form>

templates/commune/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
    <a href="{{ path('app_commune_index') }}" class="btn btn-outline-primary">back to list</a>
{{ form_end(form) }}

templates/commune/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commune{% endblock %}

{% block body %}
    <h1>Edit Commune</h1>

    {{ include('commune/_form.html.twig', {'button_label': 'Update'}) }}

    

    {{ include('commune/_delete_form.html.twig') }}
{% endblock %}

templates/commune/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commune index{% endblock %}

{% block body %}
    <h1>Commune index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Code</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commune in communes %}
            <tr>
                <td>{{ commune.id }}</td>
                <td>{{ commune.nom }}</td>
                <td>{{ commune.code }}</td>
                <td>
                    <a href="{{ path('app_commune_show', {'id': commune.id}) }}" class="btn btn-outline-primary">show</a>
                    <a href="{{ path('app_commune_edit', {'id': commune.id}) }}" class="btn btn-outline-primary">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_commune_new') }}" class="btn btn-primary">Create new</a>
{% endblock %}

templates/commune/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commune{% endblock %}

{% block body %}
    <h1>Create new Commune</h1>

    {{ include('commune/_form.html.twig') }}

{% endblock %}

templates/commune/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commune{% endblock %}

{% block body %}
    <h1>Commune</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commune.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ commune.nom }}</td>
            </tr>
            <tr>
                <th>Code</th>
                <td>{{ commune.code }}</td>
            </tr>
            <tr>
                <th>District</th>
                <td>{{ commune.district }}</td>
            </tr>
            <tr>
                <th>Région</th>
                <td>
                    {% for dist in district %}
                        {% if dist.nom == commune.district %}
                            {{ dist.region }}
                        {% endif %}
                    {% endfor %}
                </td>
            </tr>
            
        </tbody>
    </table>

    <a href="{{ path('app_commune_index') }}" class="btn btn-outline-primary">back to list</a>

    <a href="{{ path('app_commune_edit', {'id': commune.id}) }}" class="btn btn-outline-primary">edit</a>

    {{ include('commune/_delete_form.html.twig') }}
{% endblock %}