src/Entity/TesteCrud.php
<?php

namespace App\Entity;

use App\Repository\TesteCrudRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TesteCrudRepository::class)]
class TesteCrud
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_teste = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom_teste = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomTeste(): ?string
    {
        return $this->nom_teste;
    }

    public function setNomTeste(string $nom_teste): static
    {
        $this->nom_teste = $nom_teste;

        return $this;
    }

    public function getPrenomTeste(): ?string
    {
        return $this->prenom_teste;
    }

    public function setPrenomTeste(string $prenom_teste): static
    {
        $this->prenom_teste = $prenom_teste;

        return $this;
    }
}

src/Form/TesteCrudType.php
<?php

namespace App\Form;

use App\Entity\TesteCrud;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TesteCrudType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_teste')
            ->add('prenom_teste')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => TesteCrud::class,
        ]);
    }
}

src/Controller/TesteCrudController.php
<?php

namespace App\Controller;

use App\Entity\TesteCrud;
use App\Form\TesteCrudType;
use App\Repository\TesteCrudRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/teste/crud')]
class TesteCrudController extends AbstractController
{
    #[Route('/', name: 'app_teste_crud_index', methods: ['GET'])]
    public function index(TesteCrudRepository $testeCrudRepository): Response
    {
        return $this->render('teste_crud/index.html.twig', [
            'teste_cruds' => $testeCrudRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_teste_crud_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $testeCrud = new TesteCrud();
        $form = $this->createForm(TesteCrudType::class, $testeCrud);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($testeCrud);
            $entityManager->flush();

            return $this->redirectToRoute('app_teste_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('teste_crud/new.html.twig', [
            'teste_crud' => $testeCrud,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_teste_crud_show', methods: ['GET'])]
    public function show(TesteCrud $testeCrud): Response
    {
        return $this->render('teste_crud/show.html.twig', [
            'teste_crud' => $testeCrud,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_teste_crud_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, TesteCrud $testeCrud, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TesteCrudType::class, $testeCrud);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_teste_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('teste_crud/edit.html.twig', [
            'teste_crud' => $testeCrud,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_teste_crud_delete', methods: ['POST'])]
    public function delete(Request $request, TesteCrud $testeCrud, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$testeCrud->getId(), $request->request->get('_token'))) {
            $entityManager->remove($testeCrud);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_teste_crud_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/teste_crud/_delete_form.html.twig
<form method="post" action="{{ path('app_teste_crud_delete', {'id': teste_crud.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ teste_crud.id) }}">
    <button class="btn">Delete</button>
</form>

templates/teste_crud/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/teste_crud/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit TesteCrud{% endblock %}

{% block body %}
    <h1>Edit TesteCrud</h1>

    {{ include('teste_crud/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_teste_crud_index') }}">back to list</a>

    {{ include('teste_crud/_delete_form.html.twig') }}
{% endblock %}

templates/teste_crud/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}TesteCrud index{% endblock %}

{% block body %}
    <h1>TesteCrud index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_teste</th>
                <th>Prenom_teste</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for teste_crud in teste_cruds %}
            <tr>
                <td>{{ teste_crud.id }}</td>
                <td>{{ teste_crud.nomTeste }}</td>
                <td>{{ teste_crud.prenomTeste }}</td>
                <td>
                    <a href="{{ path('app_teste_crud_show', {'id': teste_crud.id}) }}">show</a>
                    <a href="{{ path('app_teste_crud_edit', {'id': teste_crud.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_teste_crud_new') }}">Create new</a>
{% endblock %}

templates/teste_crud/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New TesteCrud{% endblock %}

{% block body %}
    <h1>Create new TesteCrud</h1>

    {{ include('teste_crud/_form.html.twig') }}

    <a href="{{ path('app_teste_crud_index') }}">back to list</a>
{% endblock %}

templates/teste_crud/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}TesteCrud{% endblock %}

{% block body %}
    <h1>TesteCrud</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ teste_crud.id }}</td>
            </tr>
            <tr>
                <th>Nom_teste</th>
                <td>{{ teste_crud.nomTeste }}</td>
            </tr>
            <tr>
                <th>Prenom_teste</th>
                <td>{{ teste_crud.prenomTeste }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_teste_crud_index') }}">back to list</a>

    <a href="{{ path('app_teste_crud_edit', {'id': teste_crud.id}) }}">edit</a>

    {{ include('teste_crud/_delete_form.html.twig') }}
{% endblock %}